//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_CityDefender.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game_CityDefender.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hp {
            get {
                object obj = ResourceManager.GetObject("hp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maptest {
            get {
                object obj = ResourceManager.GetObject("maptest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 30
        ///60 30
        ///90 30
        ///270 30
        ///300 30
        ///330 30
        ///360 30
        ///390 30
        ///420 30
        ///450 30
        ///480 30
        ///510 30
        ///540 30
        ///570 30
        ///600 30
        ///630 30
        ///1020 30
        ///1050 30
        ///1080 30
        ///1110 30
        ///30 60
        ///60 60
        ///90 60
        ///270 60
        ///300 60
        ///330 60
        ///360 60
        ///390 60
        ///420 60
        ///450 60
        ///480 60
        ///510 60
        ///540 60
        ///570 60
        ///600 60
        ///630 60
        ///1080 60
        ///1110 60
        ///30 90
        ///60 90
        ///90 90
        ///270 90
        ///300 90
        ///330 90
        ///360 90
        ///390 90
        ///420 90
        ///450 90
        ///480 90
        ///510 90
        ///540 90
        ///570 90
        ///600 90
        ///630 90
        ///720 90
        ///750 90
        ///30 120
        ///60 120
        ///90 120
        ///270 120
        ///300 120
        ///330 120
        ///360 120
        ///390 120 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maptest1 {
            get {
                return ResourceManager.GetString("maptest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tankdown {
            get {
                object obj = ResourceManager.GetObject("tankdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tankleft {
            get {
                object obj = ResourceManager.GetObject("tankleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tankright {
            get {
                object obj = ResourceManager.GetObject("tankright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tankup {
            get {
                object obj = ResourceManager.GetObject("tankup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tbulletdown {
            get {
                object obj = ResourceManager.GetObject("tbulletdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tbulletleft {
            get {
                object obj = ResourceManager.GetObject("tbulletleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tbulletright {
            get {
                object obj = ResourceManager.GetObject("tbulletright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tbulletup {
            get {
                object obj = ResourceManager.GetObject("tbulletup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0
        ///30 0
        ///60 0
        ///90 0
        ///120 0
        ///150 0
        ///180 0
        ///210 0
        ///240 0
        ///270 0
        ///300 0
        ///330 0
        ///360 0
        ///390 0
        ///420 0
        ///450 0
        ///480 0
        ///510 0
        ///540 0
        ///570 0
        ///600 0
        ///630 0
        ///660 0
        ///690 0
        ///720 0
        ///750 0
        ///780 0
        ///810 0
        ///840 0
        ///870 0
        ///900 0
        ///930 0
        ///960 0
        ///990 0
        ///1020 0
        ///1050 0
        ///1080 0
        ///1110 0
        ///1140 0
        ///0 30
        ///30 30
        ///60 30
        ///90 30
        ///270 30
        ///300 30
        ///330 30
        ///360 30
        ///390 30
        ///420 30
        ///450 30
        ///480 30
        ///510 30
        ///540 30
        ///570 30
        ///600 30
        ///630 30
        ///1020 30
        ///1050 30
        ///1080 30
        ///1110 30
        ///0 60
        ///30 60
        ///60 60
        ///90 60
        ///270 60
        ///300 60
        ///330 60
        ///360 60
        ///390 60
        ///420 6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ToaDo_Map1 {
            get {
                return ResourceManager.GetString("ToaDo_Map1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450 450 0
        ///870 540 0
        ///120 30 1
        ///210 30 1
        ///390 150 1
        ///480 210 1
        ///660 30 1
        ///780 60 1
        ///840 150 1
        ///30 150 2
        ///120 210 2
        ///150 450 2
        ///30 540 2
        ///660 510 3
        ///1050 90 3
        ///1080 210 3
        ///1080 360 3
        ///1050 480 3.
        /// </summary>
        internal static string ToaDoTru_Map1 {
            get {
                return ResourceManager.GetString("ToaDoTru_Map1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap towerbullet {
            get {
                object obj = ResourceManager.GetObject("towerbullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap towerdown {
            get {
                object obj = ResourceManager.GetObject("towerdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap towerleft {
            get {
                object obj = ResourceManager.GetObject("towerleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap towerright {
            get {
                object obj = ResourceManager.GetObject("towerright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 30 1
        ///210 30 1.
        /// </summary>
        internal static string towertest {
            get {
                return ResourceManager.GetString("towertest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap towerup {
            get {
                object obj = ResourceManager.GetObject("towerup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
